In [1]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import featuretools as ft

def create_index(df):
    num=df.shape[0]
    ind=[]
    for i in range(num):
        ind.append(i)
    return(ind)

In [2]:
data1=pd.read_csv("./data/종로구/V10O1610543.csv")

In [4]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 403200 entries, 0 to 403199
Data columns (total 11 columns):
tm             403200 non-null int64
serial         403200 non-null object
flag           403200 non-null int64
pm10           403200 non-null int64
co2            403200 non-null int64
vocs           403200 non-null int64
noise          403200 non-null int64
temp           403200 non-null float64
humi           403200 non-null int64
pm25           371014 non-null float64
Unnamed: 10    0 non-null float64
dtypes: float64(3), int64(7), object(1)
memory usage: 33.8+ MB

In [5]:
jong=["V10O1610252","V10O1610546","V10O1610540","V10O1610542","V10O1610543","V10O1610544","V10O1610545","V10O1610567","V01o1610468","V10O1611289","V10O1611172","V10O1611634","V10O1611887","V10O1611639","V10O1611658","V10O1612113","V10O1611151","V10O1611145","V10O1611623","V10O1611750","V10O1611170","V10O1611684","V10O1611220","V10O1612106","V10O1611251","V10O1611173","V10O1611258","V10O1611255","V10O1611698","V10O1611722","V10O1611645"]
no=["V10O1610610","V10O1610376","V10O1610293","V10O1610356","V10O1610616","V10O1610200","V10O1610643","V10O1610642","V10O1610297","V10O1610312","V10O1610102","V10O1610351","V10O1610629","V10O1610630","V10O1611104","V10O1611097","V10O1611100","V10O1612126","V10O1611102","V10O1611652","V10O1611150","V10O1611229"]
print(len(jong))
print(len(no))

31
22

In [6]:
start_jong=[]
end_jong=[]
start_no=[]
end_no=[]
for i in jong:
    dummy1=pd.read_csv("./data/종로구/"+i+".csv")
    start_jong.append(dummy1.loc[0,"tm"])
    end_jong.append(dummy1.loc[dummy1.shape[0]-1,"tm"])
    print(dummy1.columns)
    del dummy1
    
print('------------------')
for i in no:
    dummy1=pd.read_csv("./data/노원구/"+i+".csv")
    start_no.append(dummy1.loc[0,"tm"])
    end_no.append(dummy1.loc[dummy1.shape[0]-1,"tm"])
    print(dummy1.columns)
    del dummy1

Index(['tm', 'serial', 'flag', 'pm10', 'co2', 'vocs', 'noise', 'temp', 'humi',
       'pm25', 'Unnamed: 10'],
      dtype='object')
Index(['tm', 'serial', 'flag', 'pm10', 'co2', 'vocs', 'noise', 'temp', 'humi',
       'pm25', 'Unnamed: 10'],
      dtype='object')
Index(['tm', 'serial', 'flag', 'pm10', 'co2', 'vocs', 'noise', 'temp', 'humi',
       'pm25', 'Unnamed: 10'],
      dtype='object')
Index(['tm', 'serial', 'flag', 'pm10', 'co2', 'vocs', 'noise', 'temp', 'humi',
       'pm25', 'Unnamed: 10'],
      dtype='object')
Index(['tm', 'serial', 'flag', 'pm10', 'co2', 'vocs', 'noise', 'temp', 'humi',
       'pm25', 'Unnamed: 10'],
      dtype='object')
Index(['tm', 'serial', 'flag', 'pm10', 'co2', 'vocs', 'noise', 'temp', 'humi',
       'pm25', 'Unnamed: 10'],
      dtype='object')
Index(['tm', 'serial', 'flag', 'pm10', 'co2', 'vocs', 'noise', 'temp', 'humi',
       'pm25', 'Unnamed: 10'],
      dtype='object')
Index(['tm', 'serial', 'flag', 'pm10', 'co2', 'vocs', 'noise', 'temp', 'humi',
       'pm25', 'Unnamed: 10'],
      dtype='object')
Index(['tm', 'serial', 'flag', 'pm10', 'co2', 'vocs', 'noise', 'temp', 'humi',
       'pm25', 'Unnamed: 10'],
      dtype='object')
Index(['tm', 'serial', 'flag', 'pm10', 'co2', 'vocs', 'noise', 'temp', 'humi',
       'pm25', 'Unnamed: 10'],
      dtype='object')
Index(['tm', 'serial', 'flag', 'pm10', 'co2', 'vocs', 'noise', 'temp', 'humi',
       'pm25', 'Unnamed: 10'],
      dtype='object')
Index(['tm', 'serial', 'flag', 'pm10', 'co2', 'vocs', 'noise', 'temp', 'humi',
       'pm25', 'Unnamed: 10'],
      dtype='object')
Index(['tm', 'serial', 'flag', 'pm10', 'co2', 'vocs', 'noise', 'temp', 'humi',
       'pm25', 'Unnamed: 10'],
      dtype='object')
Index(['tm', 'serial', 'flag', 'pm10', 'co2', 'vocs', 'noise', 'temp', 'humi',
       'pm25', 'Unnamed: 10'],
      dtype='object')
Index(['tm', 'serial', 'flag', 'pm10', 'co2', 'vocs', 'noise', 'temp', 'humi',
       'pm25', 'Unnamed: 10'],
      dtype='object')
Index(['tm', 'serial', 'flag', 'pm10', 'co2', 'vocs', 'noise', 'temp', 'humi',
       'pm25', 'Unnamed: 10'],
      dtype='object')
Index(['tm', 'serial', 'flag', 'pm10', 'co2', 'vocs', 'noise', 'temp', 'humi',
       'pm25', 'Unnamed: 10'],
      dtype='object')
Index(['tm', 'serial', 'flag', 'pm10', 'co2', 'vocs', 'noise', 'temp', 'humi',
       'pm25', 'Unnamed: 10'],
      dtype='object')
Index(['tm', 'serial', 'flag', 'pm10', 'co2', 'vocs', 'noise', 'temp', 'humi',
       'pm25', 'Unnamed: 10'],
      dtype='object')
Index(['tm', 'serial', 'flag', 'pm10', 'co2', 'vocs', 'noise', 'temp', 'humi',
       'pm25', 'Unnamed: 10'],
      dtype='object')
Index(['tm', 'serial', 'flag', 'pm10', 'co2', 'vocs', 'noise', 'temp', 'humi',
       'pm25', 'Unnamed: 10'],
      dtype='object')
Index(['tm', 'serial', 'flag', 'pm10', 'co2', 'vocs', 'noise', 'temp', 'humi',
       'pm25', 'Unnamed: 10'],
      dtype='object')
Index(['tm', 'serial', 'flag', 'pm10', 'co2', 'vocs', 'noise', 'temp', 'humi',
       'pm25', 'Unnamed: 10'],
      dtype='object')
Index(['tm', 'serial', 'flag', 'pm10', 'co2', 'vocs', 'noise', 'temp', 'humi',
       'pm25', 'Unnamed: 10'],
      dtype='object')
Index(['tm', 'serial', 'flag', 'pm10', 'co2', 'vocs', 'noise', 'temp', 'humi',
       'pm25', 'Unnamed: 10'],
      dtype='object')
Index(['tm', 'serial', 'flag', 'pm10', 'co2', 'vocs', 'noise', 'temp', 'humi',
       'pm25', 'Unnamed: 10'],
      dtype='object')
Index(['tm', 'serial', 'flag', 'pm10', 'co2', 'vocs', 'noise', 'temp', 'humi',
       'pm25', 'Unnamed: 10'],
      dtype='object')
Index(['tm', 'serial', 'flag', 'pm10', 'co2', 'vocs', 'noise', 'temp', 'humi',
       'pm25', 'Unnamed: 10'],
      dtype='object')
Index(['tm', 'serial', 'flag', 'pm10', 'co2', 'vocs', 'noise', 'temp', 'humi',
       'pm25', 'Unnamed: 10'],
      dtype='object')
Index(['tm', 'serial', 'flag', 'pm10', 'co2', 'vocs', 'noise', 'temp', 'humi',
       'pm25', 'Unnamed: 10'],
      dtype='object')
Index(['tm', 'serial', 'flag', 'pm10', 'co2', 'vocs', 'noise', 'temp', 'humi',
       'pm25', 'Unnamed: 10'],
      dtype='object')
------------------
Index(['tm', 'serial', 'flag', 'pm10', 'co2', 'vocs', 'noise', 'temp', 'humi',
       'pm25', 'Unnamed: 10'],
      dtype='object')
Index(['tm', 'serial', 'flag', 'pm10', 'co2', 'vocs', 'noise', 'temp', 'humi',
       'pm25', 'Unnamed: 10'],
      dtype='object')
Index(['tm', 'serial', 'flag', 'pm10', 'co2', 'vocs', 'noise', 'temp', 'humi',
       'pm25', 'Unnamed: 10'],
      dtype='object')
Index(['tm', 'serial', 'flag', 'pm10', 'co2', 'vocs', 'noise', 'temp', 'humi',
       'pm25', 'Unnamed: 10'],
      dtype='object')
Index(['tm', 'serial', 'flag', 'pm10', 'co2', 'vocs', 'noise', 'temp', 'humi',
       'pm25', 'Unnamed: 10'],
      dtype='object')
Index(['tm', 'serial', 'flag', 'pm10', 'co2', 'vocs', 'noise', 'temp', 'humi',
       'pm25', 'Unnamed: 10'],
      dtype='object')
Index(['tm', 'serial', 'flag', 'pm10', 'co2', 'vocs', 'noise', 'temp', 'humi',
       'pm25', 'Unnamed: 10'],
      dtype='object')
Index(['tm', 'serial', 'flag', 'pm10', 'co2', 'vocs', 'noise', 'temp', 'humi',
       'pm25', 'Unnamed: 10'],
      dtype='object')
Index(['tm', 'serial', 'flag', 'pm10', 'co2', 'vocs', 'noise', 'temp', 'humi',
       'pm25', 'Unnamed: 10'],
      dtype='object')
Index(['tm', 'serial', 'flag', 'pm10', 'co2', 'vocs', 'noise', 'temp', 'humi',
       'pm25', 'Unnamed: 10'],
      dtype='object')
Index(['tm', 'serial', 'flag', 'pm10', 'co2', 'vocs', 'noise', 'temp', 'humi',
       'pm25', 'Unnamed: 10'],
      dtype='object')
Index(['tm', 'serial', 'flag', 'pm10', 'co2', 'vocs', 'noise', 'temp', 'humi',
       'pm25', 'Unnamed: 10'],
      dtype='object')
Index(['tm', 'serial', 'flag', 'pm10', 'co2', 'vocs', 'noise', 'temp', 'humi',
       'pm25', 'Unnamed: 10'],
      dtype='object')
Index(['tm', 'serial', 'flag', 'pm10', 'co2', 'vocs', 'noise', 'temp', 'humi',
       'pm25', 'Unnamed: 10'],
      dtype='object')
Index(['tm', 'serial', 'flag', 'pm10', 'co2', 'vocs', 'noise', 'temp', 'humi',
       'pm25', 'Unnamed: 10'],
      dtype='object')
Index(['tm', 'serial', 'flag', 'pm10', 'co2', 'vocs', 'noise', 'temp', 'humi',
       'pm25', 'Unnamed: 10'],
      dtype='object')
Index(['tm', 'serial', 'flag', 'pm10', 'co2', 'vocs', 'noise', 'temp', 'humi',
       'pm25', 'Unnamed: 10'],
      dtype='object')
Index(['tm', 'serial', 'flag', 'pm10', 'co2', 'vocs', 'noise', 'temp', 'humi',
       'pm25', 'Unnamed: 10'],
      dtype='object')
Index(['tm', 'serial', 'flag', 'pm10', 'co2', 'vocs', 'noise', 'temp', 'humi',
       'pm25', 'Unnamed: 10'],
      dtype='object')
Index(['tm', 'serial', 'flag', 'pm10', 'co2', 'vocs', 'noise', 'temp', 'humi',
       'pm25', 'Unnamed: 10'],
      dtype='object')
Index(['tm', 'serial', 'flag', 'pm10', 'co2', 'vocs', 'noise', 'temp', 'humi',
       'pm25', 'Unnamed: 10'],
      dtype='object')
Index(['tm', 'serial', 'flag', 'pm10', 'co2', 'vocs', 'noise', 'temp', 'humi',
       'pm25', 'Unnamed: 10'],
      dtype='object')

In [7]:
jong_len=pd.DataFrame({"start_jong":start_jong,"end_jong":end_jong})
no_len=pd.DataFrame({"start_no":start_no,"end_no":end_no})
jong_len

      start_jong      end_jong
0   201804010000  201903312359
1   201804010000  201903312359
2   201804010000  201903312359
3   201804010000  201903312359
4   201804010000  201903312359
5   201804010000  201903312359
6   201804010000  201903312359
7   201804010000  201903312359
8   201804010000  201903312359
9   201804010000  201903312359
10  201804010000  201903312359
11  201804010000  201903312359
12  201804010000  201903312359
13  201804010000  201903312359
14  201804010000  201903312359
15  201804010000  201903312359
16  201804010000  201903312359
17  201804010000  201903312359
18  201804010000  201809102359
19  201804010000  201903312359
20  201804010000  201903312359
21  201804010000  201903312359
22  201804010000  201903312359
23  201804010000  201903312359
24  201804010000  201903312359
25  201804010000  201903312359
26  201804010000  201903312359
27  201804010000  201903312359
28  201804010000  201809222359
29  201804010000  201903312359
30  201804010000  201903312359

In [8]:
no_len

        start_no        end_no
0   201804010000  201807022359
1   201804010000  201903312359
2   201804010000  201903312359
3   201804010000  201903312359
4   201804010000  201903312359
5   201804010000  201903182359
6   201804010000  201903312359
7   201804010000  201903312359
8   201804010000  201903272359
9   201804010000  201903312359
10  201805070000  201903312359
11  201804090000  201903312359
12  201804010000  201903312359
13  201804010000  201903312359
14  201804010000  201903312359
15  201804010000  201903312359
16  201804010000  201903312359
17  201804010000  201903312359
18  201804010000  201903312359
19  201804010000  201806212359
20  201804010000  201903312359
21  201804010000  201903312359

In [32]:
num=0
for i in jong:
    print("------"+str(num)+"-------")
    if num==0:
        data1=pd.read_csv("./data/종로구/"+i+".csv")
        date1 = '2018-04-01 00:00'
        date2 = '2019-03-31 23:59'
        mydates = pd.date_range(date1, date2,freq='1min').tolist()
        total_data=pd.DataFrame({"tm":mydates})
        data1.tm=pd.to_datetime(data1.tm.apply(str))
        total_data=total_data.merge(data1,how="left")
        a1=total_data.tm.apply(str)
        total_data['tm2']=pd.to_datetime(a1.str.slice(0,10), format='%Y-%m-%d')
        num=num+1
            
    else:
        data2=pd.read_csv("./data/종로구/"+i+".csv")
        date1 = '2018-04-01 00:00'
        date2 = '2019-03-31 23:59'
        mydates = pd.date_range(date1, date2,freq='1min').tolist()
        total_data2=pd.DataFrame({"tm":mydates})
        data2.tm=pd.to_datetime(data2.tm.apply(str))
        total_data2=total_data2.merge(data2,how="left")
        a1=total_data2.tm.apply(str)
        total_data2['tm2']=pd.to_datetime(a1.str.slice(0,10), format='%Y-%m-%d')
        total_data=pd.concat([total_data,total_data2],axis=0)
        num=num+1

------0-------
------1-------
------2-------
------3-------
------4-------
------5-------
------6-------
------7-------
------8-------
------9-------
------10-------
------11-------
------12-------
------13-------
------14-------
------15-------
------16-------
------17-------
------18-------
------19-------
------20-------
------21-------
------22-------
------23-------
------24-------
------25-------
------26-------
------27-------
------28-------
------29-------
------30-------

In [33]:
num=0
for i in no:
    print("------"+str(num)+"-------")
    if num==0:
        data1=pd.read_csv("./data/노원구/"+i+".csv")
        date1 = '2018-04-01 00:00'
        date2 = '2019-03-31 23:59'
        mydates = pd.date_range(date1, date2,freq='1min').tolist()
        tm1=pd.to_datetime(mydates)
        total_data_2=pd.DataFrame({"tm":tm1})
        a1=data1.tm.apply(str)
        data1.tm=pd.to_datetime(a1)
        total_data_2=total_data_2.merge(data1,how="left")
        a1=total_data_2.tm.apply(str)
        total_data_2['tm2']=pd.to_datetime(a1.str.slice(0,10), format='%Y-%m-%d')
        num=num+1
            
    else:
        data2=pd.read_csv("./data/노원구/"+i+".csv")
        date1 = '2018-04-01 00:00'
        date2 = '2019-03-31 23:59'
        mydates = pd.date_range(date1, date2,freq='1min').tolist()
        tm1=pd.to_datetime(mydates)
        total_data2=pd.DataFrame({"tm":tm1})
        a1=data2.tm.apply(str)
        data2.tm=pd.to_datetime(a1)
        total_data2=total_data2.merge(data2,how="left")
        a1=total_data2.tm.apply(str)
        total_data2['tm2']=pd.to_datetime(a1.str.slice(0,10), format='%Y-%m-%d')
        total_data_2=pd.concat([total_data,total_data2],axis=0)
        num=num+1

------0-------
------1-------
------2-------
------3-------
------4-------
------5-------
------6-------
------7-------
------8-------
------9-------
------10-------
------11-------
------12-------
------13-------
------14-------
------15-------
------16-------
------17-------
------18-------
------19-------
------20-------
------21-------

In [34]:
total_data=total_data.replace([-9999,-999],np.nan)
total_data_2=total_data_2.replace([-9999,-999],np.nan)

In [35]:
total_data

,tm,serial,flag,pm10,co2,vocs,noise,temp,humi,pm25,Unnamed: 10,tm2
0,2018-04-01 00:00:00,V10O1610252,1.0,60.0,NaN,NaN,69.0,14.8,59.0,30.0,NaN,2018-04-01
1,2018-04-01 00:01:00,V10O1610252,1.0,54.0,NaN,NaN,68.0,14.8,59.0,27.0,NaN,2018-04-01
2,2018-04-01 00:02:00,V10O1610252,1.0,56.0,NaN,NaN,68.0,14.7,59.0,28.0,NaN,2018-04-01
3,2018-04-01 00:03:00,V10O1610252,1.0,66.0,NaN,NaN,69.0,14.7,59.0,33.0,NaN,2018-04-01
4,2018-04-01 00:04:00,V10O1610252,1.0,64.0,NaN,NaN,69.0,14.7,60.0,32.0,NaN,2018-04-01
5,2018-04-01 00:05:00,V10O1610252,1.0,60.0,NaN,NaN,69.0,14.8,60.0,30.0,NaN,2018-04-01
6,2018-04-01 00:06:00,V10O1610252,1.0,63.0,NaN,NaN,69.0,14.7,60.0,32.0,NaN,2018-04-01
7,2018-04-01 00:07:00,V10O1610252,1.0,55.0,NaN,NaN,69.0,14.7,60.0,28.0,NaN,2018-04-01
8,2018-04-01 00:08:00,V10O1610252,1.0,53.0,NaN,NaN,68.0,14.7,60.0,27.0,NaN,2018-04-01
9,2018-04-01 00:09:00,V10O1610252,1.0,56.0,NaN,NaN,69.0,14.7,60.0,28.0,NaN,2018-04-01
10,2018-04-01 00:10:00,V10O1610252,1.0,54.0,NaN,NaN,69.0,14.6,60.0,27.0,NaN,2018-04-01
11,2018-04-01 00:11:00,V10O1610252,1.0,57.0,NaN,NaN,69.0,14.6,61.0,29.0,NaN,2018-04-01
12,2018-04-01 00:12:00,V10O1610252,1.0,62.0,NaN,NaN,68.0,14.7,60.0,31.0,NaN,2018-04-01
13,2018-04-01 00:13:00,V10O1610252,1.0,69.0,NaN,NaN,69.0,14.6,60.0,35.0,NaN,2018-04-01
14,2018-04-01 00:14:00,V10O1610252,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-04-01
15,2018-04-01 00:15:00,V10O1610252,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-04-01
16,2018-04-01 00:16:00,V10O1610252,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-04-01
17,2018-04-01 00:17:00,V10O1610252,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-04-01
18,2018-04-01 00:18:00,V10O1610252,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-04-01
19,2018-04-01 00:19:00,V10O1610252,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-04-01
20,2018-04-01 00:20:00,V10O1610252,1.0,64.0,NaN,NaN,69.0,14.2,62.0,32.0,NaN,2018-04-01
21,2018-04-01 00:21:00,V10O1610252,1.0,60.0,NaN,NaN,69.0,14.3,62.0,30.0,NaN,2018-04-01
22,2018-04-01 00:22:00,V10O1610252,1.0,61.0,NaN,NaN,69.0,14.3,62.0,31.0,NaN,2018-04-01
23,2018-04-01 00:23:00,V10O1610252,1.0,54.0,NaN,NaN,68.0,14.4,62.0,27.0,NaN,2018-04-01
24,2018-04-01 00:24:00,V10O1610252,1.0,56.0,NaN,NaN,69.0,14.4,62.0,28.0,NaN,2018-04-01
25,2018-04-01 00:25:00,V10O1610252,1.0,59.0,NaN,NaN,69.0,14.5,62.0,30.0,NaN,2018-04-01
26,2018-04-01 00:26:00,V10O1610252,1.0,66.0,NaN,NaN,68.0,14.5,62.0,33.0,NaN,2018-04-01
27,2018-04-01 00:27:00,V10O1610252,1.0,64.0,NaN,NaN,69.0,14.5,62.0,32.0,NaN,2018-04-01
28,2018-04-01 00:28:00,V10O1610252,1.0,61.0,NaN,NaN,68.0,14.5,63.0,31.0,NaN,2018-04-01
29,2018-04-01 00:29:00,V10O1610252,1.0,64.0,NaN,NaN,69.0,14.5,62.0,32.0,NaN,2018-04-01
...,...,...,...,...,...,...,...,...,...,...,...,...
525570,2019-03-31 23:30:00,V10O1611645,1.0,27.0,NaN,NaN,49.0,4.5,28.0,15.0,NaN,2019-03-31
525571,2019-03-31 23:31:00,V10O1611645,1.0,35.0,NaN,NaN,50.0,4.5,28.0,20.0,NaN,2019-03-31
525572,2019-03-31 23:32:00,V10O1611645,1.0,35.0,NaN,NaN,49.0,4.5,28.0,20.0,NaN,2019-03-31
525573,2019-03-31 23:33:00,V10O1611645,1.0,27.0,NaN,NaN,49.0,4.5,28.0,15.0,NaN,2019-03-31
525574,2019-03-31 23:34:00,V10O1611645,1.0,32.0,NaN,NaN,50.0,4.5,28.0,18.0,NaN,2019-03-31
525575,2019-03-31 23:35:00,V10O1611645,1.0,29.0,NaN,NaN,49.0,4.5,28.0,16.0,NaN,2019-03-31
525576,2019-03-31 23:36:00,V10O1611645,1.0,35.0,NaN,NaN,50.0,4.5,27.0,20.0,NaN,2019-03-31
525577,2019-03-31 23:37:00,V10O1611645,1.0,38.0,NaN,NaN,49.0,4.5,28.0,22.0,NaN,2019-03-31
525578,2019-03-31 23:38:00,V10O1611645,1.0,37.0,NaN,NaN,50.0,4.5,28.0,21.0,NaN,2019-03-31
525579,2019-03-31 23:39:00,V10O1611645,1.0,31.0,NaN,NaN,49.0,4.5,28.0,20.0,NaN,2019-03-31
525580,2019-03-31 23:40:00,V10O1611645,1.0,23.0,NaN,NaN,50.0,4.5,28.0,15.0,NaN,2019-03-31
525581,2019-03-31 23:41:00,V10O1611645,1.0,31.0,NaN,NaN,50.0,4.5,28.0,20.0,NaN,2019-03-31
525582,2019-03-31 23:42:00,V10O1611645,1.0,32.0,NaN,NaN,49.0,4.6,28.0,21.0,NaN,2019-03-31
525583,2019-03-31 23:43:00,V10O1611645,1.0,18.0,NaN,NaN,50.0,4.5,28.0,11.0,NaN,2019-03-31
525584,2019-03-31 23:44:00,V10O1611645,1.0,31.0,NaN,NaN,50.0,4.5,28.0,20.0,NaN,2019-03-31
525585,2019-03-31 23:45:00,V10O1611645,1.0,31.0,NaN,NaN,50.0,4.5,28.0,20.0,NaN,2019-03-31
525586,2019-03-31 23:46:00,V10O1611645,1.0,31.0,NaN,NaN,50.0,4.6,28.0,20.0,NaN,2019-03-31
525587,2019-03-31 23:47:00,V10O1611645,1.0,29.0,NaN,NaN,50.0,4.5,28.0,19.0,NaN,2019-03-31
525588,2019-03-31 23:48:00,V10O1611645,1.0,51.0,NaN,NaN,49.0,4.5,28.0,33.0,NaN,2019-03-31
525589,2019-03-31 23:49:00,V10O1611645,1.0,20.0,NaN,NaN,49.0,4.5,28.0,13.0,NaN,2019-03-31
525590,2019-03-31 23:50:00,V10O1611645,1.0,71.0,NaN,NaN,50.0,4.5,28.0,46.0,NaN,2019-03-31
525591,2019-03-31 23:51:00,V10O1611645,1.0,21.0,NaN,NaN,49.0,4.5,29.0,13.0,NaN,2019-03-31
525592,2019-03-31 23:52:00,V10O1611645,1.0,18.0,NaN,NaN,50.0,4.5,29.0,11.0,NaN,2019-03-31
525593,2019-03-31 23:53:00,V10O1611645,1.0,31.0,NaN,NaN,51.0,4.5,29.0,20.0,NaN,2019-03-31
525594,2019-03-31 23:54:00,V10O1611645,1.0,26.0,NaN,NaN,50.0,4.5,29.0,17.0,NaN,2019-03-31
525595,2019-03-31 23:55:00,V10O1611645,1.0,31.0,NaN,NaN,50.0,4.4,30.0,20.0,NaN,2019-03-31
525596,2019-03-31 23:56:00,V10O1611645,1.0,23.0,NaN,NaN,49.0,4.4,30.0,15.0,NaN,2019-03-31
525597,2019-03-31 23:57:00,V10O1611645,1.0,26.0,NaN,NaN,50.0,4.4,30.0,17.0,NaN,2019-03-31
525598,2019-03-31 23:58:00,V10O1611645,1.0,18.0,NaN,NaN,49.0,4.4,31.0,11.0,NaN,2019-03-31
525599,2019-03-31 23:59:00,V10O1611645,1.0,21.0,NaN,NaN,50.0,4.4,31.0,13.0,NaN,2019-03-31

In [36]:
total_data
total_data['ind1']=create_index(total_data)

In [45]:
####연구(완료)
total_data=total_data.drop(['Unnamed: 10'],axis=1)
key1=list(set(total_data.tm2))
df1=pd.DataFrame({"tm2":key1})
df1
es=ft.EntitySet(id='sub1')
es.entity_from_dataframe(entity_id='data',dataframe=total_data,index='ind1')
es.entity_from_dataframe(entity_id='key',dataframe=df1,index='tm2')
r1=ft.Relationship(es['key']['tm2'],es["data"]['tm2'])
es=es.add_relationship(r1)

In [46]:
es

Entityset: sub1
  Entities:
    data [Rows: 16293600, Columns: 12]
    key [Rows: 365, Columns: 1]
  Relationships:
    data.tm2 -> key.tm2

In [47]:
mat1,feature1=ft.dfs(entityset=es,target_entity='key',agg_primitives=["min", "max","mean",'std','median'])

In [48]:
feature1

[<Feature: MIN(data.flag)>,
 <Feature: MIN(data.pm10)>,
 <Feature: MIN(data.co2)>,
 <Feature: MIN(data.vocs)>,
 <Feature: MIN(data.noise)>,
 <Feature: MIN(data.temp)>,
 <Feature: MIN(data.humi)>,
 <Feature: MIN(data.pm25)>,
 <Feature: MAX(data.flag)>,
 <Feature: MAX(data.pm10)>,
 <Feature: MAX(data.co2)>,
 <Feature: MAX(data.vocs)>,
 <Feature: MAX(data.noise)>,
 <Feature: MAX(data.temp)>,
 <Feature: MAX(data.humi)>,
 <Feature: MAX(data.pm25)>,
 <Feature: MEAN(data.flag)>,
 <Feature: MEAN(data.pm10)>,
 <Feature: MEAN(data.co2)>,
 <Feature: MEAN(data.vocs)>,
 <Feature: MEAN(data.noise)>,
 <Feature: MEAN(data.temp)>,
 <Feature: MEAN(data.humi)>,
 <Feature: MEAN(data.pm25)>,
 <Feature: STD(data.flag)>,
 <Feature: STD(data.pm10)>,
 <Feature: STD(data.co2)>,
 <Feature: STD(data.vocs)>,
 <Feature: STD(data.noise)>,
 <Feature: STD(data.temp)>,
 <Feature: STD(data.humi)>,
 <Feature: STD(data.pm25)>,
 <Feature: MEDIAN(data.flag)>,
 <Feature: MEDIAN(data.pm10)>,
 <Feature: MEDIAN(data.co2)>,
 <Feature: MEDIAN(data.vocs)>,
 <Feature: MEDIAN(data.noise)>,
 <Feature: MEDIAN(data.temp)>,
 <Feature: MEDIAN(data.humi)>,
 <Feature: MEDIAN(data.pm25)>]

In [49]:
mat1

,MIN(data.flag),MIN(data.pm10),MIN(data.co2),MIN(data.vocs),MIN(data.noise),MIN(data.temp),MIN(data.humi),MIN(data.pm25),MAX(data.flag),MAX(data.pm10),...,STD(data.humi),STD(data.pm25),MEDIAN(data.flag),MEDIAN(data.pm10),MEDIAN(data.co2),MEDIAN(data.vocs),MEDIAN(data.noise),MEDIAN(data.temp),MEDIAN(data.humi),MEDIAN(data.pm25)
tm2,,,,,,,,,,,,,,,,,,,,,
2018-04-01,1.0,1.0,NaN,NaN,36.0,11.1,42.0,1.0,1.0,190.0,...,8.743242,11.208872,1.0,62.0,NaN,NaN,54.0,17.4,61.0,29.0
2018-04-02,1.0,11.0,NaN,NaN,36.0,13.7,31.0,3.0,1.0,330.0,...,12.537378,8.149288,1.0,61.0,NaN,NaN,55.0,18.9,60.0,24.0
2018-04-03,1.0,1.0,NaN,NaN,36.0,13.3,43.0,1.0,1.0,232.0,...,9.921772,34.388299,1.0,60.0,NaN,NaN,55.0,18.8,64.0,16.0
2018-04-04,1.0,1.0,NaN,NaN,37.0,7.7,31.0,0.0,1.0,675.0,...,19.203245,11.064384,1.0,11.0,NaN,NaN,55.0,14.4,53.0,5.0
2018-04-05,1.0,1.0,NaN,NaN,37.0,4.7,49.0,1.0,1.0,156.0,...,11.596701,9.383805,1.0,7.0,NaN,NaN,55.0,8.7,84.0,4.0
2018-04-06,1.0,1.0,NaN,NaN,38.0,1.2,32.0,1.0,1.0,454.0,...,17.391503,16.211639,1.0,53.0,NaN,NaN,56.0,7.5,63.0,13.0
2018-04-07,1.0,6.0,NaN,NaN,37.0,-0.6,9.0,2.0,1.0,689.0,...,16.628604,13.295612,1.0,40.0,NaN,NaN,56.0,5.1,36.0,17.0
2018-04-08,1.0,1.0,NaN,NaN,37.0,-0.1,0.0,1.0,1.0,598.0,...,22.087483,11.549746,1.0,25.0,NaN,NaN,54.0,4.4,44.0,12.0
2018-04-09,1.0,1.0,NaN,NaN,36.0,0.2,0.0,1.0,1.0,318.0,...,28.066427,15.337300,1.0,38.0,NaN,NaN,55.0,9.8,39.0,26.0
2018-04-10,1.0,1.0,NaN,NaN,36.0,4.0,0.0,1.0,1.0,371.0,...,16.792520,13.246205,1.0,41.0,NaN,NaN,55.0,16.2,40.0,20.0
2018-04-11,1.0,10.0,NaN,NaN,36.0,4.0,0.0,2.0,1.0,307.0,...,24.166747,14.014991,1.0,62.0,NaN,NaN,55.0,13.6,39.0,24.0
2018-04-12,1.0,1.0,NaN,NaN,36.0,4.0,0.0,1.0,1.0,277.0,...,15.392484,9.444938,1.0,42.0,NaN,NaN,55.0,14.6,21.0,14.0
2018-04-13,1.0,1.0,NaN,NaN,37.0,4.0,0.0,1.0,1.0,338.0,...,7.448663,8.838037,1.0,30.0,NaN,NaN,55.0,16.9,17.0,13.0
2018-04-14,1.0,2.0,NaN,NaN,36.0,4.0,0.0,1.0,1.0,267.0,...,22.228529,9.433644,1.0,22.0,NaN,NaN,56.0,10.0,70.0,11.0
2018-04-15,1.0,7.0,NaN,NaN,36.0,4.0,0.0,3.0,1.0,412.0,...,15.956908,8.365173,1.0,58.0,NaN,NaN,54.0,10.7,56.0,18.0
2018-04-16,1.0,6.0,NaN,NaN,36.0,3.5,0.0,4.0,1.0,264.0,...,16.880279,9.464968,1.0,28.0,NaN,NaN,55.0,12.9,31.0,17.0
2018-04-17,1.0,1.0,NaN,NaN,37.0,4.0,0.0,1.0,1.0,488.0,...,12.642396,14.229790,1.0,52.0,NaN,NaN,55.0,13.4,29.0,27.0
2018-04-18,1.0,12.0,NaN,NaN,37.0,4.0,0.0,6.0,1.0,271.0,...,13.177418,12.594588,1.0,58.0,NaN,NaN,55.0,13.5,33.0,30.0
2018-04-19,1.0,15.0,NaN,NaN,36.0,4.0,0.0,6.0,1.0,336.0,...,13.735961,13.656393,1.0,69.0,NaN,NaN,55.0,15.2,32.0,34.0
2018-04-20,1.0,1.0,NaN,NaN,36.0,4.0,0.0,1.0,1.0,405.0,...,14.201259,21.230946,1.0,90.0,NaN,NaN,55.0,19.5,40.0,47.0
2018-04-21,1.0,3.0,NaN,NaN,37.0,4.0,0.0,1.0,1.0,383.0,...,22.169538,26.722775,1.0,64.0,NaN,NaN,55.0,19.7,20.0,34.0
2018-04-22,1.0,9.0,NaN,NaN,36.0,4.0,0.0,4.0,1.0,170.0,...,20.400687,9.579414,1.0,39.0,NaN,NaN,54.0,17.8,40.0,21.0
2018-04-23,1.0,1.0,NaN,NaN,36.0,4.0,0.0,0.0,1.0,164.0,...,16.115285,11.040013,1.0,10.0,NaN,NaN,56.0,10.2,85.0,6.0
2018-04-24,1.0,1.0,NaN,NaN,36.0,4.0,0.0,0.0,1.0,180.0,...,20.517418,7.483555,1.0,6.0,NaN,NaN,55.0,13.3,50.0,2.0
2018-04-25,1.0,1.0,NaN,NaN,36.0,4.0,0.0,1.0,1.0,202.0,...,15.565742,11.306401,1.0,28.0,NaN,NaN,55.0,16.7,29.0,20.0
2018-04-26,1.0,8.0,NaN,NaN,37.0,4.0,0.0,5.0,1.0,332.0,...,16.595888,12.691727,1.0,39.0,NaN,NaN,55.0,15.4,45.0,27.0
2018-04-27,1.0,1.0,NaN,NaN,37.0,4.0,0.0,1.0,1.0,225.0,...,14.229890,15.949818,1.0,50.0,NaN,NaN,55.0,16.4,46.0,35.0
2018-04-28,1.0,12.0,NaN,NaN,37.0,4.0,0.0,6.0,1.0,220.0,...,20.510774,20.962574,1.0,61.0,NaN,NaN,55.0,16.2,36.0,37.0
2018-04-29,1.0,13.0,NaN,NaN,37.0,4.0,0.0,6.0,1.0,204.0,...,14.061137,15.734619,1.0,58.0,NaN,NaN,54.0,17.6,36.0,31.0
2018-04-30,1.0,17.0,NaN,NaN,35.0,4.0,0.0,10.0,1.0,313.0,...,13.697345,17.362462,1.0,84.0,NaN,NaN,55.0,19.7,52.0,58.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2019-03-02,1.0,8.0,NaN,NaN,37.0,0.0,0.0,5.0,1.0,400.0,...,14.922365,39.830513,1.0,176.0,NaN,NaN,56.0,9.4,33.0,125.0
2019-03-03,1.0,15.0,NaN,NaN,36.0,1.6,0.0,10.0,1.0,602.0,...,13.783261,49.890933,1.0,139.0,NaN,NaN,54.0,11.4,35.0,98.0
2019-03-04,1.0,15.0,NaN,NaN,36.0,4.9,0.0,10.0,1.0,700.0,...,14.713805,90.412795,1.0,243.0,NaN,NaN,55.0,10.7,43.0,170.0
2019-03-05,1.0,26.0,NaN,NaN,36.0,4.3,0.0,17.0,1.0,698.0,...,12.556641,102.294943,1.0,329.0,NaN,NaN,56.0,9.3,60.0,236.0
2019-03-06,1.0,26.0,NaN,NaN,37.0,5.0,0.0,19.0,1.0,575.0,...,6.341775,47.142056,1.0,179.0,NaN,NaN,56.0,9.7,52.0,125.0
2019-03-07,1.0,1.0,NaN,NaN,37.0,2.7,0.0,1.0,1.0,334.0,...,14.588232,32.072161,1.0,65.0,NaN,NaN,56.0,8.2,41.0,43.0
2019-03-08,1.0,1.0,NaN,NaN,37.0,0.4,0.0,1.0,1.0,370.0,...,12.557552,22.780334,1.0,55.0,NaN,NaN,56.0,6.9,34.0,30.0
2019-03-09,1.0,1.0,NaN,NaN,37.0,0.0,0.0,1.0,1.0,355.0,...,15.976875,28.693281,1.0,43.0,NaN,NaN,56.0,9.7,26.0,27.0
2019-03-10,1.0,1.0,NaN,NaN,36.0,6.6,0.0,1.0,1.0,332.0,...,14.030279,32.737304,1.0,57.0,NaN,NaN,54.0,11.2,22.0,36.0
2019-03-11,1.0,3.0,NaN,NaN,36.0,3.0,0.0,1.0,1.0,334.0,...,10.363536,19.647407,1.0,66.0,NaN,NaN,55.0,8.1,53.0,40.0
2019-03-12,1.0,1.0,NaN,NaN,37.0,-1.4,4.0,1.0,1.0,316.0,...,24.402122,32.763380,1.0,86.0,NaN,NaN,56.0,6.0,66.0,55.0
2019-03-13,1.0,1.0,NaN,NaN,37.0,-1.8,8.0,1.0,1.0,319.0,...,11.185015,11.165267,1.0,54.0,NaN,NaN,56.0,4.4,34.0,15.0
2019-03-14,1.0,2.0,NaN,NaN,37.0,-1.8,0.0,1.0,1.0,647.0,...,14.155421,14.638522,1.0,55.0,NaN,NaN,55.0,7.8,42.0,24.0
2019-03-15,1.0,1.0,NaN,NaN,36.0,0.7,0.0,1.0,1.0,206.0,...,20.116025,17.084877,1.0,64.0,NaN,NaN,56.0,6.6,73.0,32.0
2019-03-16,1.0,1.0,NaN,NaN,37.0,0.0,0.0,1.0,1.0,314.0,...,16.414918,15.805056,1.0,40.0,NaN,NaN,56.0,5.7,62.0,27.0
2019-03-17,1.0,2.0,NaN,NaN,37.0,2.0,0.0,1.0,1.0,201.0,...,19.624889,11.989444,1.0,39.0,NaN,NaN,55.0,7.1,49.0,22.0
2019-03-18,1.0,2.0,NaN,NaN,36.0,0.3,0.0,1.0,1.0,138.0,...,18.237979,9.784178,1.0,35.0,NaN,NaN,55.0,8.8,34.0,20.0
2019-03-19,1.0,1.0,NaN,NaN,36.0,3.2,0.0,1.0,1.0,211.0,...,15.753368,19.079849,1.0,56.0,NaN,NaN,55.0,11.6,43.0,31.0
2019-03-20,1.0,1.0,NaN,NaN,37.0,6.8,0.0,1.0,1.0,207.0,...,15.051458,19.065484,1.0,79.0,NaN,NaN,56.0,11.2,75.0,56.0
2019-03-21,1.0,1.0,NaN,NaN,36.0,0.2,40.0,1.0,1.0,252.0,...,16.923661,17.864733,1.0,36.0,NaN,NaN,56.0,9.6,73.0,26.0
2019-03-22,1.0,1.0,NaN,NaN,37.0,-2.2,15.0,1.0,1.0,141.0,...,13.639311,10.452023,1.0,34.0,NaN,NaN,56.0,4.3,36.0,19.0
2019-03-23,1.0,1.0,NaN,NaN,37.0,-0.5,0.0,1.0,1.0,157.0,...,13.677733,7.383095,1.0,24.0,NaN,NaN,56.0,4.8,42.0,15.0
2019-03-24,1.0,1.0,NaN,NaN,37.0,-1.5,2.0,1.0,1.0,139.0,...,10.547906,7.267853,1.0,29.0,NaN,NaN,55.0,5.5,40.0,13.0
2019-03-25,1.0,1.0,NaN,NaN,36.0,2.2,0.0,1.0,1.0,211.0,...,8.020695,13.377171,1.0,50.0,NaN,NaN,56.0,9.1,52.0,28.0
2019-03-26,1.0,3.0,NaN,NaN,37.0,6.4,0.0,1.0,1.0,252.0,...,21.607605,13.691207,1.0,67.0,NaN,NaN,55.0,12.4,43.0,38.0
2019-03-27,1.0,23.0,NaN,NaN,37.0,7.6,0.0,14.0,1.0,225.0,...,12.114372,15.785514,1.0,86.0,NaN,NaN,56.0,12.1,63.0,52.0
2019-03-28,1.0,12.0,NaN,NaN,36.0,4.4,1.0,6.0,1.0,584.0,...,23.485489,27.645814,1.0,75.0,NaN,NaN,56.0,10.2,42.0,43.0
2019-03-29,1.0,9.0,NaN,NaN,37.0,4.3,0.0,3.0,1.0,251.0,...,11.026978,7.386335,1.0,38.0,NaN,NaN,55.0,9.7,29.0,18.0
2019-03-30,1.0,2.0,NaN,NaN,37.0,1.7,0.0,1.0,1.0,139.0,...,13.173698,11.402728,1.0,38.0,NaN,NaN,57.0,6.0,67.0,23.0
2019-03-31,1.0,2.0,NaN,NaN,37.0,1.2,14.0,1.0,1.0,159.0,...,19.302792,12.814024,1.0,36.0,NaN,NaN,55.0,5.1,47.0,24.0

In [55]:
####연구(완료)
total_data_2=total_data_2.replace([-9999,-999],np.nan)
total_data_2=total_data_2.drop(['Unnamed: 10'],axis=1)
key1=list(set(total_data_2.tm2))
df1=pd.DataFrame({"tm2":key1})
df1
es=ft.EntitySet(id='sub1')
es.entity_from_dataframe(entity_id='data',dataframe=total_data_2,index='ind1')
es.entity_from_dataframe(entity_id='key',dataframe=df1,index='tm2')
r1=ft.Relationship(es['key']['tm2'],es["data"]['tm2'])
es=es.add_relationship(r1)
es

Entityset: sub1
  Entities:
    data [Rows: 16819200, Columns: 12]
    key [Rows: 365, Columns: 1]
  Relationships:
    data.tm2 -> key.tm2

In [56]:
mat2,feature2=ft.dfs(entityset=es,target_entity='key',agg_primitives=["min", "max","mean",'std','median'])

In [57]:
mat2

,MIN(data.flag),MIN(data.pm10),MIN(data.co2),MIN(data.vocs),MIN(data.noise),MIN(data.temp),MIN(data.humi),MIN(data.pm25),MAX(data.flag),MAX(data.pm10),...,STD(data.humi),STD(data.pm25),MEDIAN(data.flag),MEDIAN(data.pm10),MEDIAN(data.co2),MEDIAN(data.vocs),MEDIAN(data.noise),MEDIAN(data.temp),MEDIAN(data.humi),MEDIAN(data.pm25)
tm2,,,,,,,,,,,,,,,,,,,,,
2018-04-01,1.0,1.0,NaN,NaN,36.0,11.1,42.0,1.0,1.0,190.0,...,8.788537,11.279946,1.0,62.0,NaN,NaN,54.0,17.4,61.0,29.0
2018-04-02,1.0,11.0,NaN,NaN,36.0,13.7,31.0,3.0,1.0,330.0,...,12.527415,8.138292,1.0,61.0,NaN,NaN,54.0,18.9,60.0,24.0
2018-04-03,1.0,1.0,NaN,NaN,36.0,13.3,43.0,1.0,1.0,232.0,...,9.886031,33.885597,1.0,61.0,NaN,NaN,55.0,18.8,64.0,16.0
2018-04-04,1.0,1.0,NaN,NaN,37.0,7.7,31.0,0.0,1.0,675.0,...,19.162138,11.147819,1.0,11.0,NaN,NaN,55.0,14.4,53.0,5.0
2018-04-05,1.0,1.0,NaN,NaN,37.0,4.7,49.0,1.0,1.0,156.0,...,11.583452,9.450897,1.0,7.0,NaN,NaN,55.0,8.7,84.0,4.0
2018-04-06,1.0,1.0,NaN,NaN,38.0,1.2,32.0,1.0,1.0,454.0,...,17.374143,16.483029,1.0,53.0,NaN,NaN,55.0,7.5,63.0,13.0
2018-04-07,1.0,6.0,NaN,NaN,37.0,-0.6,9.0,2.0,1.0,689.0,...,16.627555,13.289882,1.0,40.0,NaN,NaN,55.0,5.1,35.0,17.0
2018-04-08,1.0,1.0,NaN,NaN,37.0,-0.1,0.0,1.0,1.0,598.0,...,22.100819,11.527206,1.0,25.0,NaN,NaN,54.0,4.4,44.0,12.0
2018-04-09,1.0,1.0,NaN,NaN,36.0,0.2,0.0,1.0,1.0,318.0,...,28.082239,15.351733,1.0,38.0,NaN,NaN,55.0,9.8,40.0,26.0
2018-04-10,1.0,1.0,NaN,NaN,36.0,4.0,0.0,1.0,1.0,371.0,...,16.757048,13.220538,1.0,41.0,NaN,NaN,55.0,16.2,40.0,20.0
2018-04-11,1.0,10.0,NaN,NaN,36.0,4.0,0.0,2.0,1.0,307.0,...,24.091657,14.329376,1.0,63.0,NaN,NaN,55.0,13.6,39.0,24.0
2018-04-12,1.0,1.0,NaN,NaN,36.0,4.0,0.0,1.0,1.0,277.0,...,15.393355,9.443720,1.0,43.0,NaN,NaN,55.0,14.6,21.0,14.0
2018-04-13,1.0,1.0,NaN,NaN,37.0,4.0,0.0,1.0,1.0,338.0,...,7.440709,8.836115,1.0,30.0,NaN,NaN,55.0,16.9,17.0,13.0
2018-04-14,1.0,1.0,NaN,NaN,36.0,4.0,0.0,1.0,1.0,267.0,...,22.131343,9.476973,1.0,23.0,NaN,NaN,55.0,10.1,70.0,11.0
2018-04-15,1.0,1.0,NaN,NaN,36.0,4.0,0.0,1.0,1.0,412.0,...,15.864520,8.494652,1.0,58.0,NaN,NaN,54.0,10.7,56.0,18.0
2018-04-16,1.0,1.0,NaN,NaN,36.0,3.5,0.0,1.0,1.0,264.0,...,16.948563,9.529457,1.0,29.0,NaN,NaN,55.0,12.9,31.0,17.0
2018-04-17,1.0,1.0,NaN,NaN,37.0,4.0,0.0,1.0,1.0,488.0,...,12.627548,14.428639,1.0,53.0,NaN,NaN,55.0,13.4,29.0,27.0
2018-04-18,1.0,12.0,NaN,NaN,37.0,4.0,0.0,5.0,1.0,277.0,...,13.217559,13.043188,1.0,59.0,NaN,NaN,55.0,13.5,33.0,31.0
2018-04-19,1.0,15.0,NaN,NaN,36.0,4.0,0.0,6.0,1.0,336.0,...,13.809125,14.465852,1.0,70.0,NaN,NaN,55.0,15.2,32.0,34.0
2018-04-20,1.0,1.0,NaN,NaN,36.0,4.0,0.0,1.0,1.0,405.0,...,14.133919,22.265111,1.0,91.0,NaN,NaN,55.0,19.5,39.0,47.0
2018-04-21,1.0,3.0,NaN,NaN,37.0,4.0,0.0,1.0,1.0,383.0,...,22.256467,27.640352,1.0,65.0,NaN,NaN,55.0,19.7,20.0,34.0
2018-04-22,1.0,1.0,NaN,NaN,36.0,4.0,0.0,2.0,1.0,170.0,...,20.357028,9.626976,1.0,39.0,NaN,NaN,54.0,17.8,40.0,21.0
2018-04-23,1.0,1.0,NaN,NaN,36.0,4.0,0.0,0.0,1.0,164.0,...,15.846231,11.057294,1.0,10.0,NaN,NaN,55.0,10.2,85.0,6.0
2018-04-24,1.0,1.0,NaN,NaN,36.0,4.0,0.0,0.0,1.0,180.0,...,20.424476,7.631583,1.0,6.0,NaN,NaN,55.0,13.3,50.0,2.0
2018-04-25,1.0,1.0,NaN,NaN,36.0,4.0,0.0,1.0,1.0,202.0,...,15.610408,11.469884,1.0,28.0,NaN,NaN,55.0,16.8,30.0,20.0
2018-04-26,1.0,1.0,NaN,NaN,37.0,4.0,0.0,1.0,1.0,332.0,...,16.567766,12.882639,1.0,39.0,NaN,NaN,55.0,15.4,45.0,27.0
2018-04-27,1.0,1.0,NaN,NaN,37.0,4.0,0.0,1.0,1.0,227.0,...,14.174199,16.385215,1.0,51.0,NaN,NaN,55.0,16.4,46.0,36.0
2018-04-28,1.0,1.0,NaN,NaN,37.0,4.0,0.0,1.0,1.0,220.0,...,20.478548,21.108132,1.0,61.0,NaN,NaN,55.0,16.2,36.0,37.0
2018-04-29,1.0,13.0,NaN,NaN,37.0,4.0,0.0,6.0,1.0,204.0,...,13.978077,15.973213,1.0,58.0,NaN,NaN,54.0,17.6,36.0,32.0
2018-04-30,1.0,17.0,NaN,NaN,35.0,4.0,0.0,10.0,1.0,313.0,...,13.601164,18.157617,1.0,85.0,NaN,NaN,55.0,19.8,52.0,58.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2019-03-02,1.0,8.0,NaN,NaN,37.0,0.0,0.0,5.0,1.0,400.0,...,14.966453,39.524105,1.0,173.0,NaN,NaN,55.0,9.4,33.0,123.0
2019-03-03,1.0,15.0,NaN,NaN,36.0,1.6,0.0,10.0,1.0,602.0,...,13.765494,49.356869,1.0,138.0,NaN,NaN,54.0,11.5,35.0,98.0
2019-03-04,1.0,15.0,NaN,NaN,36.0,4.9,0.0,10.0,1.0,700.0,...,14.635797,89.637742,1.0,239.0,NaN,NaN,55.0,10.7,43.0,167.0
2019-03-05,1.0,26.0,NaN,NaN,36.0,4.3,0.0,17.0,1.0,698.0,...,12.531713,100.982213,1.0,327.0,NaN,NaN,55.0,9.3,60.0,234.0
2019-03-06,1.0,26.0,NaN,NaN,37.0,5.0,0.0,19.0,1.0,575.0,...,6.398041,46.760714,1.0,179.0,NaN,NaN,55.0,9.7,52.0,125.0
2019-03-07,1.0,1.0,NaN,NaN,37.0,2.7,0.0,1.0,1.0,334.0,...,14.600258,31.658593,1.0,64.0,NaN,NaN,55.0,8.2,41.0,43.0
2019-03-08,1.0,1.0,NaN,NaN,37.0,0.4,0.0,1.0,1.0,370.0,...,12.645900,22.456907,1.0,55.0,NaN,NaN,56.0,6.9,34.0,30.0
2019-03-09,1.0,1.0,NaN,NaN,37.0,0.0,0.0,1.0,1.0,355.0,...,15.902243,28.282070,1.0,43.0,NaN,NaN,56.0,9.6,26.0,27.0
2019-03-10,1.0,1.0,NaN,NaN,36.0,6.6,0.0,1.0,1.0,332.0,...,13.901700,32.248857,1.0,57.0,NaN,NaN,54.0,11.1,22.0,37.0
2019-03-11,1.0,3.0,NaN,NaN,36.0,3.0,0.0,1.0,1.0,334.0,...,10.297700,19.582047,1.0,67.0,NaN,NaN,55.0,8.1,53.0,40.0
2019-03-12,1.0,1.0,NaN,NaN,37.0,-1.4,4.0,1.0,1.0,316.0,...,24.375321,33.104360,1.0,86.0,NaN,NaN,55.0,6.0,66.0,55.0
2019-03-13,1.0,1.0,NaN,NaN,37.0,-1.8,8.0,1.0,1.0,319.0,...,11.220648,11.106093,1.0,55.0,NaN,NaN,55.0,4.4,34.0,15.0
2019-03-14,1.0,2.0,NaN,NaN,37.0,-1.8,0.0,1.0,1.0,647.0,...,14.177806,14.525331,1.0,55.0,NaN,NaN,55.0,7.8,42.0,24.0
2019-03-15,1.0,1.0,NaN,NaN,36.0,0.7,0.0,1.0,1.0,206.0,...,20.107251,17.145116,1.0,64.0,NaN,NaN,56.0,6.6,73.0,32.0
2019-03-16,1.0,1.0,NaN,NaN,37.0,0.0,0.0,1.0,1.0,314.0,...,16.468996,15.728628,1.0,40.0,NaN,NaN,56.0,5.7,63.0,27.0
2019-03-17,1.0,2.0,NaN,NaN,37.0,2.0,0.0,1.0,1.0,201.0,...,19.615030,11.920693,1.0,39.0,NaN,NaN,55.0,7.1,49.0,22.0
2019-03-18,1.0,2.0,NaN,NaN,36.0,0.3,0.0,1.0,1.0,138.0,...,18.234237,9.723628,1.0,36.0,NaN,NaN,55.0,8.8,34.0,20.0
2019-03-19,1.0,1.0,NaN,NaN,36.0,3.2,0.0,1.0,1.0,211.0,...,15.715166,19.172115,1.0,56.0,NaN,NaN,55.0,11.6,43.0,31.0
2019-03-20,1.0,1.0,NaN,NaN,37.0,6.8,0.0,1.0,1.0,207.0,...,15.070062,18.881113,1.0,79.0,NaN,NaN,56.0,11.2,75.0,56.0
2019-03-21,1.0,1.0,NaN,NaN,36.0,0.2,40.0,1.0,1.0,252.0,...,16.938566,17.739786,1.0,36.0,NaN,NaN,56.0,9.6,73.0,26.0
2019-03-22,1.0,1.0,NaN,NaN,37.0,-2.2,15.0,1.0,1.0,141.0,...,13.602159,10.417680,1.0,34.0,NaN,NaN,56.0,4.3,36.0,19.0
2019-03-23,1.0,1.0,NaN,NaN,37.0,-0.5,0.0,1.0,1.0,157.0,...,13.675806,7.382562,1.0,24.0,NaN,NaN,56.0,4.7,42.0,15.0
2019-03-24,1.0,1.0,NaN,NaN,37.0,-1.5,2.0,1.0,1.0,139.0,...,10.578334,7.238031,1.0,29.0,NaN,NaN,55.0,5.5,40.0,13.0
2019-03-25,1.0,1.0,NaN,NaN,36.0,2.2,0.0,1.0,1.0,211.0,...,7.969586,13.382706,1.0,50.0,NaN,NaN,55.0,9.1,52.0,28.0
2019-03-26,1.0,3.0,NaN,NaN,37.0,6.4,0.0,1.0,1.0,252.0,...,21.569842,13.643795,1.0,67.0,NaN,NaN,55.0,12.4,42.0,38.0
2019-03-27,1.0,23.0,NaN,NaN,37.0,7.6,0.0,14.0,1.0,225.0,...,12.061626,15.629599,1.0,86.0,NaN,NaN,56.0,12.1,63.0,53.0
2019-03-28,1.0,12.0,NaN,NaN,36.0,4.4,1.0,6.0,1.0,584.0,...,23.444709,27.434940,1.0,75.0,NaN,NaN,55.0,10.2,42.0,44.0
2019-03-29,1.0,9.0,NaN,NaN,37.0,4.3,0.0,3.0,1.0,251.0,...,10.897510,7.390537,1.0,38.0,NaN,NaN,55.0,9.7,29.0,18.0
2019-03-30,1.0,2.0,NaN,NaN,37.0,1.7,0.0,1.0,1.0,139.0,...,13.188876,11.541533,1.0,38.0,NaN,NaN,56.0,6.0,67.0,24.0
2019-03-31,1.0,2.0,NaN,NaN,37.0,1.2,14.0,1.0,1.0,159.0,...,19.344077,12.862048,1.0,36.0,NaN,NaN,54.0,5.1,47.0,24.0

In [63]:
total_data.to_csv("jong.csv")

In [64]:
total_data_2.to_csv("no.csv")

In [61]:
total_data_2

,ind1,tm,serial,flag,pm10,co2,vocs,noise,temp,humi,pm25,tm2
0,0,2018-04-01 00:00:00,V10O1610252,1.0,60.0,NaN,NaN,69.0,14.8,59.0,30.0,2018-04-01
1,1,2018-04-01 00:01:00,V10O1610252,1.0,54.0,NaN,NaN,68.0,14.8,59.0,27.0,2018-04-01
2,2,2018-04-01 00:02:00,V10O1610252,1.0,56.0,NaN,NaN,68.0,14.7,59.0,28.0,2018-04-01
3,3,2018-04-01 00:03:00,V10O1610252,1.0,66.0,NaN,NaN,69.0,14.7,59.0,33.0,2018-04-01
4,4,2018-04-01 00:04:00,V10O1610252,1.0,64.0,NaN,NaN,69.0,14.7,60.0,32.0,2018-04-01
5,5,2018-04-01 00:05:00,V10O1610252,1.0,60.0,NaN,NaN,69.0,14.8,60.0,30.0,2018-04-01
6,6,2018-04-01 00:06:00,V10O1610252,1.0,63.0,NaN,NaN,69.0,14.7,60.0,32.0,2018-04-01
7,7,2018-04-01 00:07:00,V10O1610252,1.0,55.0,NaN,NaN,69.0,14.7,60.0,28.0,2018-04-01
8,8,2018-04-01 00:08:00,V10O1610252,1.0,53.0,NaN,NaN,68.0,14.7,60.0,27.0,2018-04-01
9,9,2018-04-01 00:09:00,V10O1610252,1.0,56.0,NaN,NaN,69.0,14.7,60.0,28.0,2018-04-01
10,10,2018-04-01 00:10:00,V10O1610252,1.0,54.0,NaN,NaN,69.0,14.6,60.0,27.0,2018-04-01
11,11,2018-04-01 00:11:00,V10O1610252,1.0,57.0,NaN,NaN,69.0,14.6,61.0,29.0,2018-04-01
12,12,2018-04-01 00:12:00,V10O1610252,1.0,62.0,NaN,NaN,68.0,14.7,60.0,31.0,2018-04-01
13,13,2018-04-01 00:13:00,V10O1610252,1.0,69.0,NaN,NaN,69.0,14.6,60.0,35.0,2018-04-01
14,14,2018-04-01 00:14:00,V10O1610252,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-04-01
15,15,2018-04-01 00:15:00,V10O1610252,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-04-01
16,16,2018-04-01 00:16:00,V10O1610252,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-04-01
17,17,2018-04-01 00:17:00,V10O1610252,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-04-01
18,18,2018-04-01 00:18:00,V10O1610252,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-04-01
19,19,2018-04-01 00:19:00,V10O1610252,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-04-01
20,20,2018-04-01 00:20:00,V10O1610252,1.0,64.0,NaN,NaN,69.0,14.2,62.0,32.0,2018-04-01
21,21,2018-04-01 00:21:00,V10O1610252,1.0,60.0,NaN,NaN,69.0,14.3,62.0,30.0,2018-04-01
22,22,2018-04-01 00:22:00,V10O1610252,1.0,61.0,NaN,NaN,69.0,14.3,62.0,31.0,2018-04-01
23,23,2018-04-01 00:23:00,V10O1610252,1.0,54.0,NaN,NaN,68.0,14.4,62.0,27.0,2018-04-01
24,24,2018-04-01 00:24:00,V10O1610252,1.0,56.0,NaN,NaN,69.0,14.4,62.0,28.0,2018-04-01
25,25,2018-04-01 00:25:00,V10O1610252,1.0,59.0,NaN,NaN,69.0,14.5,62.0,30.0,2018-04-01
26,26,2018-04-01 00:26:00,V10O1610252,1.0,66.0,NaN,NaN,68.0,14.5,62.0,33.0,2018-04-01
27,27,2018-04-01 00:27:00,V10O1610252,1.0,64.0,NaN,NaN,69.0,14.5,62.0,32.0,2018-04-01
28,28,2018-04-01 00:28:00,V10O1610252,1.0,61.0,NaN,NaN,68.0,14.5,63.0,31.0,2018-04-01
29,29,2018-04-01 00:29:00,V10O1610252,1.0,64.0,NaN,NaN,69.0,14.5,62.0,32.0,2018-04-01
...,...,...,...,...,...,...,...,...,...,...,...,...
525570,16819170,2019-03-31 23:30:00,V10O1611229,1.0,35.0,NaN,NaN,52.0,4.6,27.0,23.0,2019-03-31
525571,16819171,2019-03-31 23:31:00,V10O1611229,1.0,37.0,NaN,NaN,50.0,4.6,28.0,24.0,2019-03-31
525572,16819172,2019-03-31 23:32:00,V10O1611229,1.0,17.0,NaN,NaN,51.0,4.6,28.0,11.0,2019-03-31
525573,16819173,2019-03-31 23:33:00,V10O1611229,1.0,37.0,NaN,NaN,50.0,4.6,28.0,24.0,2019-03-31
525574,16819174,2019-03-31 23:34:00,V10O1611229,1.0,19.0,NaN,NaN,51.0,4.6,28.0,12.0,2019-03-31
525575,16819175,2019-03-31 23:35:00,V10O1611229,1.0,42.0,NaN,NaN,50.0,4.5,28.0,27.0,2019-03-31
525576,16819176,2019-03-31 23:36:00,V10O1611229,1.0,23.0,NaN,NaN,50.0,4.5,28.0,15.0,2019-03-31
525577,16819177,2019-03-31 23:37:00,V10O1611229,1.0,34.0,NaN,NaN,50.0,4.5,28.0,22.0,2019-03-31
525578,16819178,2019-03-31 23:38:00,V10O1611229,1.0,14.0,NaN,NaN,51.0,4.5,28.0,9.0,2019-03-31
525579,16819179,2019-03-31 23:39:00,V10O1611229,1.0,26.0,NaN,NaN,50.0,4.5,28.0,17.0,2019-03-31
525580,16819180,2019-03-31 23:40:00,V10O1611229,1.0,27.0,NaN,NaN,51.0,4.5,28.0,18.0,2019-03-31
525581,16819181,2019-03-31 23:41:00,V10O1611229,1.0,29.0,NaN,NaN,50.0,4.5,29.0,19.0,2019-03-31
525582,16819182,2019-03-31 23:42:00,V10O1611229,1.0,21.0,NaN,NaN,50.0,4.5,29.0,14.0,2019-03-31
525583,16819183,2019-03-31 23:43:00,V10O1611229,1.0,26.0,NaN,NaN,50.0,4.5,29.0,17.0,2019-03-31
525584,16819184,2019-03-31 23:44:00,V10O1611229,1.0,23.0,NaN,NaN,50.0,4.4,29.0,15.0,2019-03-31
525585,16819185,2019-03-31 23:45:00,V10O1611229,1.0,21.0,NaN,NaN,50.0,4.4,29.0,14.0,2019-03-31
525586,16819186,2019-03-31 23:46:00,V10O1611229,1.0,27.0,NaN,NaN,50.0,4.4,30.0,18.0,2019-03-31
525587,16819187,2019-03-31 23:47:00,V10O1611229,1.0,25.0,NaN,NaN,51.0,4.4,30.0,16.0,2019-03-31
525588,16819188,2019-03-31 23:48:00,V10O1611229,1.0,50.0,NaN,NaN,50.0,4.4,30.0,33.0,2019-03-31
525589,16819189,2019-03-31 23:49:00,V10O1611229,1.0,29.0,NaN,NaN,51.0,4.4,30.0,19.0,2019-03-31
525590,16819190,2019-03-31 23:50:00,V10O1611229,1.0,23.0,NaN,NaN,50.0,4.4,30.0,15.0,2019-03-31
525591,16819191,2019-03-31 23:51:00,V10O1611229,1.0,23.0,NaN,NaN,50.0,4.4,30.0,15.0,2019-03-31
525592,16819192,2019-03-31 23:52:00,V10O1611229,1.0,23.0,NaN,NaN,50.0,4.4,30.0,15.0,2019-03-31
525593,16819193,2019-03-31 23:53:00,V10O1611229,1.0,31.0,NaN,NaN,51.0,4.4,30.0,20.0,2019-03-31
525594,16819194,2019-03-31 23:54:00,V10O1611229,1.0,21.0,NaN,NaN,50.0,4.4,31.0,14.0,2019-03-31
525595,16819195,2019-03-31 23:55:00,V10O1611229,1.0,23.0,NaN,NaN,50.0,4.4,31.0,15.0,2019-03-31
525596,16819196,2019-03-31 23:56:00,V10O1611229,1.0,25.0,NaN,NaN,50.0,4.4,31.0,16.0,2019-03-31
525597,16819197,2019-03-31 23:57:00,V10O1611229,1.0,19.0,NaN,NaN,50.0,4.3,32.0,12.0,2019-03-31
525598,16819198,2019-03-31 23:58:00,V10O1611229,1.0,21.0,NaN,NaN,50.0,4.3,32.0,14.0,2019-03-31
525599,16819199,2019-03-31 23:59:00,V10O1611229,1.0,38.0,NaN,NaN,50.0,4.3,32.0,25.0,2019-03-31